name: Subbu solar system

on: 
    workflow_dispatch: 
    push: 

jobs:
    unit-testing:
        name: sample job for testing
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the repo
              uses: actions/checkout@v4

            - name: Setup the node
              uses: actions/setup-node@v3
              with:
                node-version: 20

            - name: node install the packages
              run: |
                npm install

            - name: Unit Testing
              run: npm test

            - name: Archive Test Result
              uses: actions/upload-artifact@v3
              with:
               name: Mocha-Test-Result
               path: test-results.xml

